### ISSUE TITLE
Adding ESLint and Prettier GitHub Actions

### ISSUE THREAD

**Issue by iamrajiv** [Graph-Visualization/graph-api#14]
ESLint is a static code analysis tool for identifying problematic patterns found in JavaScript code:

- You will find bugs and errors before they happen.
- You will spend less time testing new features.
- Your code (and your team's code) will be more consistent.

Prettier is a very popular code formatter which uses very opinionated but sensible styles to format your code and prevent the ongoing debates about code styles.

**Comment by iamrajiv** [comment]
@yashrsharma44 I want to work on this issue.

**Comment by yashrsharma44** [comment]
Cool, this seems to be nice addition, go ahead with this!
