### ISSUE TITLE
Prettier is failing in the Github Actions

### ISSUE THREAD

**Issue by yashrsharma44** [Graph-Visualization/graph-api#20]
We have observed that all the checks are failing for prettier linting. Some issues are there with the github action yaml file for prettier.

**Comment by iamrajiv** [comment]
@yashrsharma44 I think it's related to Personal access tokens. Adding this will solve the issue

```yml
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
