### ISSUE TITLE
Add Contributors name 

### ISSUE THREAD

**Issue by codewithvk** [Graph-Visualization/graph-api#26]
Add Contributors name using a bot.

**Comment by codewithvk** [comment]
@yashrsharma44 Can you assign me?

**Comment by yashrsharma44** [comment]
Cool, can you add some details about the implementation?

**Comment by codewithvk** [comment]
![Capture](https://user-images.githubusercontent.com/61119120/101893945-75760200-3bcb-11eb-8504-4d99d5773708.PNG)
I can add like this. If agreed then let me inform so I can start my work.

**Comment by yashrsharma44** [comment]
Sounds awesome, move ahead with this!
